name: AntaresPrison
version: 1.2
api-version: 1.15
depend: [PlaceholderAPI, Multiverse-Core]
authors: [piotrwyrw, nathen418]
load: POSTWORLD
main: org.piotrwyrw.antares.prison.AntaresPrison
commands:
  prison:
    description: Plugin main command