name: AntaresPrison
version: 1.5
api-version: 1.15
depend: [PlaceholderAPI, Multiverse-Core]
authors: [piotrwyrw, nathen418]
description: Thanks to the whole Antares community for helping to develop this plugin!
load: POSTWORLD
main: org.piotrwyrw.antares.prison.AntaresPrison
commands:
  prisons:
    description: Plugin main command