name: AntaresPrison
version: 1.4
api-version: 1.15
depend: [PlaceholderAPI, Multiverse-Core]
authors: [piotrwyrw, nathen418]
description: Special thanks to the whole Antares community for helping to test and improve this plugin.
load: POSTWORLD
main: org.piotrwyrw.antares.prison.AntaresPrison
commands:
  prisons:
    description: Plugin main command