name: AntaresPrison
version: 1.3
api-version: 1.15
depend: [PlaceholderAPI]
authors: [piotrwyrw, nathen418]
load: POSTWORLD
main: org.piotrwyrw.antares.prison.AntaresPrison
commands:
  prisons:
    description: Plugin main command